language: node_js
node_js:
  - "8.9.1"
# Speeds up build time since it doesn't have to install the same packages again.
cache:
  directories:
    - node_modules

install:
  - npm install -g codecov
  - npm install

script:
  - npm run test && codecov
